// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ZaracartproductstestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void zaraaddingshoestocart() {
    driver.get("https://zara.com/il");
    driver.findElement(By.linkText("חיפוש")).click();
    driver.findElement(By.id("search-products-form-combo-input")).click();
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys("SHOES");
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,481)");
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,\'נעלי בלרינה מעור\')]")));
    }
    vars.put("x", driver.findElement(By.xpath("//a[contains(.,\'נעלי בלרינה מעור\')]")).getText());
    System.out.println(vars.get("x").toString());
    js.executeScript("window.scrollTo(0,558)");

    driver.findElement(By.cssSelector(".carousel__item:nth-child(3) .product-add-to-cart__button-icon")).click();
    driver.findElement(By.cssSelector(".carousel__item:nth-child(2) .product-add-to-cart__button-icon")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("#product-size-selector-267208856-toggle-button .product-add-to-cart__button-icon")));
    }
    driver.findElement(By.cssSelector("#product-size-selector-267208856-toggle-button .product-add-to-cart__button-icon")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".product-cart-buttons__add-to-cart > .zds-button__lines-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".product-cart-buttons__add-to-cart span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".product-cart-buttons__add-to-cart span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".zds-alert-dialog__button > .zds-button__lines-wrapper")).click();
    driver.findElement(By.cssSelector("#product-size-selector-267208856-item-6 .product-size-info__main-label")).click();
    driver.findElement(By.cssSelector(".product-cart-buttons__add-to-cart span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".product-cart-buttons__add-to-cart span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,482)");
    driver.findElement(By.cssSelector(".add-to-cart-notification__cart-button span")).click();
    js.executeScript("window.scrollTo(0,0)");
    assertThat(driver.findElement(By.cssSelector(".shop-cart-item-header__description")).getText(), is("vars.get(\"x\").toString()"));
  }
  @Test
  public void zarafindingproduct() {
    driver.get("https://zara.com/il");
    driver.findElement(By.linkText("חיפוש")).click();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("search-products-form-combo-input")));
    driver.findElement(By.id("search-products-form-combo-input")).click();
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys("SHOES");
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,481)");
    {
//      WebDriverWait wait = new WebDriverWait(driver, null);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,\'נעלי בלרינה מעור\')]")));
    }
    vars.put("x", driver.findElement(By.xpath("//a[contains(.,\'נעלי בלרינה מעור\')]")).getText());
    System.out.println(vars.get("x").toString());
  }

  @Test
  public void zarafindingproductnew() {
    driver.get("https://zara.com/il");
    driver.findElement(By.linkText("חיפוש")).click();
    driver.findElement(By.id("search-products-form-combo-input")).click();
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys("SHOES");
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys(Keys.ENTER);
    js.executeScript("window.scrollTo(0,481)");
    {
      WebDriverWait wait = new WebDriverWait(driver, NaN);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,\'נעלי בלרינה מעור\')]")));
    }
    vars.put("x", driver.findElement(By.xpath("//a[contains(.,\'נעלי בלרינה מעור\')]")).getText());
    System.out.println(vars.get("x").toString());
  }
  

}
